const moduloA = require('./127_moduloA.js')
const moduloB = require('./127_moduloB.js')

console.log(moduloA.ola)
console.log(moduloA.bemVindo)
console.log(moduloA.ateLogo)
console.log(moduloA)
console.log(moduloB.bomDia)
console.log(moduloB.boaNoite())
console.log(moduloB)